---

configure_dotfiles: false
configure_terminal: false
configure_osx: true
osx_script: "~/scripts/osx.sh"
configure_node_with_volta: true
install_rust: true
dotfiles_repo: https://github.com/SaiKrishnaMohan7/dotfiles.git
dotfiles_repo_accept_hostkey: true

# run brew upgrade every time before this is run
homebrew_installed_packages:
  - git
  - go
  - nmap
  - volta
  - neofetch
  - jq
  - tldr
  - tree
  - htop
  - kubectl
  - helm
  - minikube
  - terraform
  - azure-cli
  - awscli
  - wireshark
  - yarn
  - yadm # dotfile management

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - docker
  - firefox
  - slack
  - obsidian
  # - discord only on personal mac
  - amethyst # tiling management
  - caffiene
  - 1password
  - 1password-cli
  - postman
  - postico # GUI for postgres
  - drawio
  - vagrant # Type 2 virtualization
  - virtualbox # Type 2 virtualization
  - visual-studio-code
  - iterm2
