- name: Install common GUI apps (casks)
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - iterm2
    - rectangle    # may move away from this if raycast is better
    - docker
    - obsidian
    - caffeine
    - drawio
    - firefox
    - raycast
    - postman
    - 1password
    - 1password-cli
    - visual-studio-code
    - vagrant
    - magic-wormhole
